---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    app: my-pract-app
spec:
  containers:
    - name: my-httpd-container
      image: httpd  
      ports:
        - containerPort: 80  
...  