---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    app: my-pract-app
spec:
  containers:
    - name: my-nginx-container
    image: nginx  
    port:
      container: 80  
    - name: my-httpd-container
    image: httpd
    port: 
      container: 80
    - name: my-tomcat-container
    image: tomcat
    port: 
      container: 8080
...  