---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    app: my-pract-app
spec:
  containers:
    - name: my-nginx-container
      image: nginx  
      port:
        containerPort: 80  
...  