---
apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels: 
    app: my-pract-app
spec:
  containers:
    - name: my-nginx-container
      image: nginx  
      port:
        containerPort: 80  
    - name: my-httpd-container
      image: httpd
      port: 
        containerPort: 80
    - name: my-tomcat-container
      image: tomcat
      port: 
        containerPort: 8080
...  